language: c

compiler: gcc
sudo: required

jobs:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: bionic

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libelf1 libelf-dev nasm valgrind

script:
  - make test
  - make lint
